apiVersion: apps/v1
kind: Deployment
metadata:
  name: fomichev-ikbo-20-21
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fomichev-ikbo-20-21
  template:
    metadata:
      labels:
        app: fomichev-ikbo-20-21
    spec:
      containers:
      - name: fomichev-ikbo-20-21-container
        image: fomichev-ikbo-20-21-obraz
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

        