apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: graylog
spec:
  type: NodePort
  selector:
    app: elastic
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30001
  - name: "9300"
    port: 9300
    targetPort: 9300
    nodePort: 30002