apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:4.3
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 12201
              protocol: UDP
          env:
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92" #123456
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: "http://graylog.graylog:9000/"
            - name: GRAYLOG_PASSWORD_SECRET
              value: g0ABP9MJnWCjWtBX9JHFgjKAmD3wGXP3E0JQNOKlquDHnCn5689QAF8rRL66HacXLPA6fvwMY8BZoVVw0JqHnSAZorDDOdCk
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongo:27017/graylog
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: gelf-udp
      port: 12201
      targetPort: 12201
      protocol: UDP
  selector:
    app: graylog