apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: graylog
  labels:
    service: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  namespace: graylog
  name: mongo
spec:
  selector:
    service: mongo
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017