apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.port}}
      targetPort: 8080