apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: fomichev-image:latest
        imagePullPolicy: IfNotPresent
        name: frontend
        volumeMounts:
        - name: passwd-volume
          readOnly: true
          mountPath: "/etc/redis-passwd"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            cpu: "1.0"
            memory: "1G"
          limits:
            cpu: "1.0"
            memory: "1G"
        env:
        - name: JOURNAL_ENTRIES
          valueFrom:
           configMapKeyRef:
              name: frontend-config
              key: journalEntries
      volumes:
        - name: passwd-volume
          secret:
           secretName: redis-passwd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
