apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: "romanfomic/config-server:latest"
        ports:
        - containerPort: 8888
        env:
        - name: JAVA_OPTS
          value: "-Xms1g -Xmx2g -XX:MaxMetaspaceSize=256m"
        resources:
          requests:
            memory: "600Mi"
            cpu: "600m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: config-server
spec:
  type: LoadBalancer
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888