version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "fomic_db"
      POSTGRES_USER: "fomic"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./queue_realization_4.sql:/docker-entrypoint-initdb.d/queue_realization.sql
    ports:
      - "5432:5432"