version: '3'

services:
  db:
    build: .
    environment:
      POSTGRES_DB: "fomic_db"
      POSTGRES_USER: "fomic"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./functions1.sql:/docker-entrypoint-initdb.d/functions.sql
    ports:
      - "5432:5432"