apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: fomichev-sd-ikbo2021
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
      - -cpus
      - "2"